# config.toml

title = "yokai_battle_config"

battle_id = 2001
mysql_dsn = "root:@(host.docker.internal:3306)/db_battle"
http_listen_addr = ":8081"

# battle evironment
micro_registry = "mdns"
micro_transport = "tcp"
micro_broker = "http"
micro_server_id = 2001
